version: '3.9'
volumes:
  dbbackups:
  postgis-data:

services:
  db:
    image: postgis/postgis:12-3.1-alpine
    volumes:
      - postgis-data:/var/lib/postgresql
      - dbbackups:/backups
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=gis_db
      - POSTGRES_USER=nest_learning
      - POSTGRES_PASSWORD=qwerty
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    ports:
      - "5432:5432"
    healthcheck:
      test: "exit 0"